-- Tables mirror the portfolio entities. Existing rows are preserved. The date
-- conversion addresses the legacy experience.start_date/end_date mismatch.

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) UNIQUE,
    profile_image VARCHAR(255),
    enabled BOOLEAN DEFAULT TRUE,
    role_id BIGINT REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS about (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(3000),
    email VARCHAR(255),
    phone VARCHAR(255),
    location VARCHAR(255),
    github_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    profile_image VARCHAR(255),
    resume_url VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4000),
    technology VARCHAR(255) NOT NULL,
    github_url VARCHAR(255),
    live_url VARCHAR(255),
    image_url VARCHAR(255),
    featured BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    percentage INTEGER,
    icon VARCHAR(255),
    category VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    designation VARCHAR(255) NOT NULL,
    employment_type VARCHAR(255),
    location VARCHAR(255),
    start_date DATE,
    end_date DATE,
    currently_working BOOLEAN DEFAULT FALSE,
    description VARCHAR(3000),
    technologies VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree VARCHAR(255) NOT NULL,
    institution VARCHAR(255) NOT NULL,
    field_of_study VARCHAR(255),
    start_year INTEGER,
    end_year INTEGER,
    grade VARCHAR(255),
    description VARCHAR(3000)
);

CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    issuer VARCHAR(240) NOT NULL,
    issue_date DATE,
    description VARCHAR(3000),
    credential_url VARCHAR(1000)
);

-- Empty strings become NULL. Unparseable dates abort and roll back the
-- migration; no existing date text is silently discarded.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'experience'
          AND column_name = 'start_date'
          AND data_type <> 'date'
    ) THEN
        ALTER TABLE experience
            ALTER COLUMN start_date TYPE DATE
            USING NULLIF(BTRIM(start_date::text), '')::date;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'experience'
          AND column_name = 'end_date'
          AND data_type <> 'date'
    ) THEN
        ALTER TABLE experience
            ALTER COLUMN end_date TYPE DATE
            USING NULLIF(BTRIM(end_date::text), '')::date;
    END IF;
END $$;

INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_USER') ON CONFLICT (name) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_projects_featured ON projects (featured);
CREATE INDEX IF NOT EXISTS idx_experience_start_date ON experience (start_date);
