export const catalog = {
  projects: {
    title: "Projects",
    intro: "Add project descriptions, technologies, and public links.",
    endpoint: "/admin/projects",
    titleField: "title",
    subtitleField: "technology",
    descriptionField: "description",
    fields: [
      { name: "title", label: "Project title", type: "text", required: true },
      { name: "technology", label: "Technologies", type: "text", required: true, hint: "Separate technologies with commas." },
      { name: "description", label: "Description", type: "textarea", required: true, maxLength: 4000, full: true },
      { name: "githubUrl", label: "GitHub URL", type: "url" },
      { name: "liveUrl", label: "Live URL", type: "url" },
      { name: "imageUrl", label: "Image URL", type: "url" },
      { name: "featured", label: "Feature this project", type: "checkbox" },
    ],
  },
  skills: {
    title: "Skills",
    intro: "Set a name, category, and optional level for each skill.",
    endpoint: "/admin/skills",
    titleField: "name",
    subtitleField: "category",
    fields: [
      { name: "name", label: "Skill name", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "percentage", label: "Level (%)", type: "number", min: 0, max: 100 },
      { name: "icon", label: "Icon name or URL", type: "text" },
    ],
  },
  experience: {
    title: "Experience",
    intro: "Manage work experience and training entries. Dates use YYYY-MM-DD.",
    endpoint: "/admin/experience",
    titleField: "designation",
    subtitleField: "company",
    dateFields: ["startDate", "endDate", "currentlyWorking"],
    descriptionField: "description",
    fields: [
      { name: "designation", label: "Role or designation", type: "text", required: true },
      { name: "company", label: "Company", type: "text", required: true },
      { name: "employmentType", label: "Employment type", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "startDate", label: "Start date", type: "date" },
      { name: "endDate", label: "End date", type: "date", disabledWhenCurrent: true },
      { name: "currentlyWorking", label: "Currently working here", type: "checkbox" },
      { name: "technologies", label: "Technologies", type: "text" },
      { name: "description", label: "Description", type: "textarea", maxLength: 3000, full: true },
    ],
  },
  education: {
    title: "Education",
    intro: "Manage degrees, institutions, and year ranges.",
    endpoint: "/admin/education",
    titleField: "degree",
    subtitleField: "institution",
    yearFields: ["startYear", "endYear"],
    descriptionField: "description",
    fields: [
      { name: "degree", label: "Degree or qualification", type: "text", required: true },
      { name: "institution", label: "Institution", type: "text", required: true },
      { name: "fieldOfStudy", label: "Field of study", type: "text" },
      { name: "startYear", label: "Start year", type: "number", min: 1800, max: 2200 },
      { name: "endYear", label: "End year", type: "number", min: 1800, max: 2200 },
      { name: "grade", label: "Grade", type: "text" },
      { name: "description", label: "Description", type: "textarea", maxLength: 3000, full: true },
    ],
  },
  certifications: {
    title: "Certifications",
    intro: "Manage credentials and links to verify them.",
    endpoint: "/admin/certifications",
    titleField: "title",
    subtitleField: "issuer",
    dateFields: ["issueDate"],
    descriptionField: "description",
    fields: [
      { name: "title", label: "Certification", type: "text", required: true },
      { name: "issuer", label: "Issuer", type: "text", required: true },
      { name: "issueDate", label: "Issue date", type: "date" },
      { name: "credentialUrl", label: "Credential URL", type: "url", maxLength: 1000 },
      { name: "description", label: "Description", type: "textarea", maxLength: 3000, full: true },
    ],
  },
};
